"""empty message

Revision ID: 352b4b9fc4ef
Revises: b193ed6aa815
Create Date: 2020-06-02 23:46:31.969540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352b4b9fc4ef'
down_revision = 'b193ed6aa815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('slug', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'slug')
    # ### end Alembic commands ###
